### ISSUE TITLE
Get and pass all events from event store to node-cqrs-eventdenormalizer

### ISSUE THREAD

**Issue by josh0707** [adrai/node-eventstore#104]
Hello,

Thank you for your library.
The issue concerns how node-eventstore transmits events to node-cqrs-eventdenormalizer.

I want to rebuild a viewmodel by extracting all the events from the store.

For eventdenormalizer I can do:
`eventdenormalizer.clear(function(err) {});
eventdenormalizer.replay([/* ordered array of events */], function (err) { if (err) { console.log(err); } });`

For node-eventstore I can use to fetch all the events:
`es.getEvents()`

However, I didn't find the solution to pass my events from the event store to my eventdenormalizer.
Do I need to use eventstore.setEventToDispatched() for each event or is there another way?

Thanks.

Josh

**Comment by adrai** [comment]
It depends on your system but basically you need to wrap for example es.getEvents() with a rest service or a dedicated channel on the messageBus.
Then when you want to rebuild you can ask that service to return your events by streaming or I would recommend to implement some sort of pagination...

**Comment by josh0707** [comment]
Thanks.
Basically, I could do:
client ---Rest (rebuild request)--> Host Server: rebuild-readmodel method (request events) ---MessageBus--> EventStore (es.getEvents()) ---MessageBus--> Host Server: rebuild-readmodel method (eventdenormalizer.clear();eventdenormalizer.replay())

The rebuild-readmodel method would be accessible via a Rest request to the Host Server and would send a messages to the EventStore to get the events before requesting the Eventdenormalizer to perform a replay.
Does it sound right? ...

**Comment by adrai** [comment]
There is no correct or incorrect... just do what best fits in your system.
Usually in my systems I do not request for a replay from client side. I do it on the operations side (i.e. while deploying a new release) => so each time a new ReadModel have to be (re)created the denormalizer processes are started with a special environment variable or flag and then they will request all events (in pages) via REST from a "replay-service" that queries the events from the eventstore.

**Comment by josh0707** [comment]
Thank you for the explanation.
