### ISSUE TITLE
Memory issue when loading next events from eventstore

### ISSUE THREAD

**Issue by repkins** [adrai/node-eventstore#112]
Hello, @adrai!

I came across with some sort of memory related issues when I loading next page of events from eventstore. The issue becomes more serious when I call  `.next()` method of events array multiple of **thousands** times. As more and more followed by calls of method, memory usage **grows** of node process, which suggests something is causing a memory leak. Apparently, calling `.next()` on every returned events array of that page many multiple times causes this.

Please, take a look! Because of this for me is unsafe to use `.next()` to retrieve next events when there is thousands pages of them, forcing to use a `.getEventsSince()` workaround.

**Comment by adrai** [comment]
I would be really happy if you could start to analyze this based on your use case...
A sample app that shows the issue you are describing would help a lot.

**Comment by repkins** [comment]
Actually have done this so far. The conclusion is (trying to explain).. it holds recursive references to variables in closures declared in previous `.next()` invocation, even they're not used in current invocation, which results in chained reference to previous closures ending with first invocation where first events loaded and `.next()` method is declared. So currently declared `.next()` method function body holds closure of parent function body where has references to previous events array with `.next()` method.

Comparison of multiple heapdumps really helped to isolate source of "leak".

I would suggest avoid recursive declaring of `.next()` method repeatly. Instead, declare that function body once and build logic to swap previous events to new, dereferencing prevous them, and can be later garbage collected.

**Comment by adrai** [comment]
Wow, seems you already did a good analysis... Do you want to submit a PR?

**Comment by repkins** [comment]
As there seems is needed some redesign I think it's up to you to do so.

**Comment by repkins** [comment]
`.getEventsSince()` maybe?

**Comment by repkins** [comment]
Well, it seems memory usage does not grow that dramatically after tried given code.

**Comment by adrai** [comment]
v1.12.6

**Comment by wrobel** [comment]
I assume this commit broke something. It got pretty late debugging this now but I need to reverted back to 1.12.5 in order to get the usage of .next() working. I'm using store.getEvents(0, 100, (err, evts) => {...}) in order to start fetching events and I call .next((err, evts) => {...}) once the first batch of fetched events was denormalized. Unfortunately the second .next() call does call the callback I provided to store.getEvents() instead of the callback given to .next(). I think the passed parameters did not get cleaned up properly and I noticed that .next(...) somehow had two callback rather than the one it should have. It's too late for me to debug any further but in case the problem is not obvious I'm happy to dig deeper later.

**Comment by adrai** [comment]
couldn't reproduce it...

do you mean something like this?

I get:
------ called this callback
------ called next callback
------ called next 2 callback

```javascript
                    es.getEvents({ aggregate: 'myAgg', context: 'myCont' }, 0, 3, function (err, evts) {
                      console.log('------ called this callback')
                      evts.next(function (err, nextEvts) {
                        console.log('------ called next callback')
                        nextEvts.next(function (err, nextNextEvts) {
                          console.log('------ called next 2 callback')
                        });
                      });
                    });
```

**Comment by wrobel** [comment]
@adrai Sorry for the delay. I followed up on my report now, analyzed the issue and provided a pull request in #116
