### ISSUE TITLE
Internal publisher only publishes event payload

### ISSUE THREAD

**Issue by chrisandrews7** [adrai/node-eventstore#121]
The internal dispatcher current only publishes the [event.payload](https://github.com/adrai/node-eventstore/blob/master/lib/eventDispatcher.js#L36).
Is there a reason why it doesn't publish the other event information i.e. aggregateId, aggregate etc?

Context: Am using the dispatcher to publish to a message broker.

**Comment by adrai** [comment]
event.payload should be what you're looking for if you want to publish to a message broker.

The other information is an "internal" wrap of what you should send via a message broker (https://github.com/adrai/node-eventstore/blob/master/lib/event.js#L38)

If you need the information like aggregateId, etc... you have to put them in there.

**Comment by chrisandrews7** [comment]
Ok thanks for the prompt clarification.  👍
