### ISSUE TITLE
Disconnecting

### ISSUE THREAD

**Issue by chrisandrews7** [adrai/node-eventstore#123]
Is there a way of disconnecting from the event store?
The store [disconnect method](https://github.com/adrai/node-eventstore/blob/master/lib/databases/mongodb.js#L177) is there, but its not exposed via the eventstore. 

Doing some integration tests and want to disconnect from the store when done.

**Comment by adrai** [comment]
https://github.com/adrai/node-eventstore/blob/master/test/eventstoreTest.js#L920

**Comment by chrisandrews7** [comment]
👍 Thanks
