### ISSUE TITLE
Upgrade Lodash Version to Fix Prototype Pollution Vulnerability

### ISSUE THREAD

**Issue by emmkong** [adrai/node-eventstore#135]
The version of lodash lib uses in this project contains low-risk `Prototype Pollution` Vulnerability. see [https://www.npmjs.com/advisories/577](https://www.npmjs.com/advisories/577), please upgrade it to the latest version if possible. Thanks

**Comment by nanov** [comment]
The version this projects uses ( 4.17.10 ) is the latest. 
I guess your warnings come not directly from this project, but from the (node-cqrs-domain)[https://github.com/adrai/node-cqrs-domain] which depends on this project, but it's dependency isn't updated.

I will update it now, and hopefully those vulnerability warnings will be gone.

**Comment by nanov** [comment]
I've just published an update for [node-cqrs-domain](https://github.com/adrai/node-cqrs-domain) which addresses those issues.
