### ISSUE TITLE
Auto-reconnect MongoDB

### ISSUE THREAD

**Issue by lysender** [adrai/node-eventstore#152]
Is there an option to reconnect to MongoDB after it has been disconnected briefly? I just tried to stop/start the MongoDB server and it doesn't seem to recover after disconnecting.

Below is my example code.

```javascript
const store = eventstore({
  type: 'mongodb',
  url: process.env.DATABASE_URL,
  eventsCollectionName: EVENTS_COLLECTION_NAME,
  snapshotsCollectionName: SNAPSHOTS_COLLECTION_NAME,
  transactionsCollectionName: TRANSACTIONS_COLLECTION_NAME,
  timeout: 10000,
  maxSnapshotsCount: 10,
  reconnectTries: 30,
  reconnectInterval: 1000,
  autoReconnect: true,
  useNewUrlParser: true
});

store.init();

store.on('connect', () => {
  console.log('Event store connected');
});

store.on('disconnect', () => {
  console.log('Event store disconnected');
});
````

Note: I'm using NestJS as a framework, if that matters.

**Comment by adrai** [comment]
put the mongodb driver specific options in a sub object options:

{
   timeout: 20000,
   options: {
      autoReconnect: true
   }
}

**Comment by lysender** [comment]
@adrai confirmed that it works! 

I noticed that `store.on('connect') ` doesn't get called when reconnected but `store.on('disconnect')` gets called every time it gets disconnected.

However, I get the information that I need. All good. Thanks!
