### ISSUE TITLE
Flag for dropping existing data when initializing?

### ISSUE THREAD

**Issue by gingobaum** [adrai/node-eventstore#155]
Is it possible (or are there any chances) to provide a flag that signals eventstore to drop all existing data and/or databases, so we can start from zero?

For example in sequelize there is a flag called *force*, that creates that behavior.

I think, it would be great for development and testing purposes.

**Comment by nanov** [comment]
I believe ```es.store.clear(cb)``` is what you are looking for.

**Comment by gingobaum** [comment]
Yes, looks like it. 
Maybe it should be mentioned in the documentation?

And how about a options flag for the user's convenience?

**Comment by nanov** [comment]
I truly don't see any point in such options flag.

However, as long as it is falsy by default i also have noting against it, PRs are welcome.
