### ISSUE TITLE
Method for testing if there are any or how many events are stored?

### ISSUE THREAD

**Issue by gingobaum** [adrai/node-eventstore#156]
Is there some other (convenient) way to check, if the store already contains some events or how many, than the following?

```javascript
es.getEvents(0, -1, (err, events) => {
    if(length) {
        // contains 'length' events
    }
    // is empty
})
```

**Comment by nanov** [comment]
TL:DR;

Not really.

Explanation

it really depends on what you want, the events count, see if specific events are there or something else, basically you need to query those based on the database adapter for more complex scenarios.
Implementing additional query methods is not a bad idea ( count, byName ), is that what you are looking for?

**Comment by gingobaum** [comment]
The method could be useful in some way. 
Actually I simply would like to see, if there are already some events stored I can replay, or if I even have to initialize my application (with default users or something else).

**Comment by nanov** [comment]
to see if there are some events ( no matter which ) :
```js
// ( es6 helper method )
const hasAnyEvents = async es =>  new Promise((resolve, reject) => es.getEvents(0,1, (err, events) => {
  if (err)
    return reject(err);
  resolve(!!events.length);
}));
```

should do it, and then you can use it like that:
```js
if (await hasAnyEvents(es)) {
  // do something
}
```

**Comment by gingobaum** [comment]
I am using such function now and it is not that big of a deal. The only thing that comes to mind would be code duplication, if it's used in different parts or projects.

**Comment by nanov** [comment]
Well, again as i mentioned in an other issue of yours, PRs are welcome.
