### ISSUE TITLE
Question: Can I query snapshots by date?

### ISSUE THREAD

**Issue by ScripterSugar** [adrai/node-eventstore#165]
Hello. 

I'm building my own event-store architecture based on this library and currently working on handling various error scenarios that might occur in real-life situations.

I'm wondering how can I rebuild my read models with optimized solution using snapshots, when I have to rebuild only read models based on specific aggregates (EX: "User") with snapshot data made before specific timestamp.

As far as I know, the library currently only supports to load snapshots based on event revisions but timestamp.

What's the best way to accomplish this task? Is there any way to load snapshots based on max timestamp?

**Comment by adrai** [comment]
This is not possible right now, because the state in your snapshot will/should look completely different to what you may use on the readmodel side.
Snapshots are only used to optimize aggregate loading to ensure the business rules...

**Comment by ScripterSugar** [comment]
For those who wondering how I solved this problem:

I ended up creating another event stream with dynamically generated context having unix timestamp as revision for only storing snapshots and made my own encapsulated method to create snapshot query with those unix timestamps.

**Comment by adrai** [comment]
It's just not used, like intended, but if it works for you...
