### ISSUE TITLE
MongoDB: "revision" field type should be casted to number when createSnapshot

### ISSUE THREAD

**Issue by ScripterSugar** [adrai/node-eventstore#166]
Hi.

I've experienced wrong order issue while querying snapshots as I stored my snapshots with "string" typed revisions, and I think the library should force revision inputs in number type because string typed revisions cause sort issues when we query documents like this:

```
> db.snapshots.find({ aggregateId: "NEWSTREAMID", context: "User_Snapshot"}).sort({revision: -1}).pretty()
{
        "_id" : "5f2138f1f3969e93542e2b2c",
        "id" : "5f2138f1f3969e93542e2b2c",
        "streamId" : "NEWSTREAMID",
        "aggregateId" : "NEWSTREAMID",
        "aggregate" : "User",
        "context" : "User_Snapshot",
        "commitStamp" : ISODate("2020-07-29T08:53:05.651Z"),
        "revision" : "24",
        "version" : null,
        "data" : "24"
}
{
        "_id" : "5f213990f3969e93542e2b2e",
        "id" : "5f213990f3969e93542e2b2e",
        "streamId" : "NEWSTREAMID",
        "aggregateId" : "NEWSTREAMID",
        "aggregate" : "User",
        "context" : "User_Snapshot",
        "commitStamp" : ISODate("2020-07-29T08:55:44.575Z"),
        "revision" : "124",
        "version" : null,
        "data" : "124"
}
...
```

document with revision "24" comes out first even if there's a document with revision "124" and there's no errors nor warnings when I save my snapshot with string-value revisions.

**Comment by adrai** [comment]
How are you creating snapshots?

How do you call es.createSnapshot()

**Comment by adrai** [comment]
it’s the same revision value passed when creating the snapshot

**Comment by ScripterSugar** [comment]
@adrai 
Yes I found it out yesterday. What I want to say is that since the store implementation (at least mongodb implementation) assumes that revisions are in number format, it's better to throw errors when people try to push revision value in another format rather than number.

**Comment by adrai** [comment]
Feel free to provide a PR.
