### ISSUE TITLE
How to pass 'options' into the custom implementation of 'Store'?

### ISSUE THREAD

**Issue by nizachon** [adrai/node-eventstore#27]
Adriano,

Following your instructions (https://github.com/adrai/node-eventstore#own-db-implementation), I was able to have *EventStore* use my own implementation of *Store*.

But after being a happy camper for a few days, now I don't see a way to pass *options* into my *Store*'s (and also, *EventStore*'s) constructor. 

https://github.com/adrai/node-eventstore/blob/master/index.js#L7 :

```javascript
function getSpecificStore(options) {
  options = options || {};

  if (options.prototype instanceof Base) {
    return options;
  }
```

https://github.com/adrai/node-eventstore/blob/master/index.js#L48https://github.com/adrai/node-eventstore/blob/master/index.js#L48 :

```javascript
module.exports = function(options) {
  options = options || {};

  var Store;

  try {
    Store = getSpecificStore(options);
  } catch (err) {
    throw err;
  }

  return new Eventstore(options, new Store(options));
};

module.exports.Store = Base;
```

It appears that when using the custom *Store* implementation the way you recommend, what gets passed as *options*  into the factory method and *EventStore* constructor, is the constructor of the custom *Store*. Then the same *Store* constructor gets called with **itself** as the value of *options*...

Am I missing something here?

Thanks,
-Leo

**Comment by adrai** [comment]
ok, I see the problem... What do you think on having the "own implementation" as second argument?

**Comment by adrai** [comment]
No, this is a bad idea, this will break the api of some other cqrs modules... but we could do something like:

```javascript
var es = require('eventstore')({
  host: 'localhost',
  ownImplementation: Store
});
```

**Comment by nizachon** [comment]
So *type* will be interpreted as a constructor function, correct?

**Comment by nizachon** [comment]
https://github.com/adrai/node-eventstore#own-db-implementation :

Shouldn't it be *MyDB* instead of *Store*:

```javascript
var es = require('eventstore')({
  type: Store
});
// es.init...
```

**Comment by adrai** [comment]
Yes



Il giorno 27-gen-2015, alle ore 23:52, nizachon <notifications@github.com<mailto:notifications@github.com>> ha scritto:


https://github.com/adrai/node-eventstore#own-db-implementation :

Shouldn't it be MyDB instead of Store:

var es = require('eventstore')({
  type: Store
});
// es.init...

-
