### ISSUE TITLE
Cannot use custom store when it is brought in as a dependency (v1.1.3)

### ISSUE THREAD

**Issue by nizachon** [adrai/node-eventstore#28]
Adriano,

Current implementation fails when I have more than one version of *eventstore* module in the project's *node-modules* tree. If the project makes use both of *cqrs-domain* and *my-custom-store*, which both require *eventstore*, then the project's *node-modules* tree will look like this:

* cqrs-domain
  * eventstore (1)
* my-custom-store
  * eventstore (2)

Then this check:

```javascript
if (options.type && options.type.prototype instanceof Base) {
    return options.type;
}
```

will always come back negative, as *Base* is defined in *eventstore (1)*, while *options.type* is a sub-class of *Base* from *eventstore (2)*

How do you feel about replacing it with this:

```javascript
if (options.type && typeof options.type === 'function') {
    return options.type;
}
```

Best,
-Leo

**Comment by adrai** [comment]
ok, v1.1.4

**Comment by nizachon** [comment]
Thank you!
