### ISSUE TITLE
Only Getting Undispatched Items per StreamID

### ISSUE THREAD

**Issue by NilsFrkal** [adrai/node-eventstore#45]
Hi, not an issue, but I couldn't find a better way to ask this question. Is there any way that I can get only the undispatched items per streamId? It works in the "add - commit" scenario but not if I do not want to add an item. the getUndispatched function returns ALL undispatched item for the es and I could loop over this, but I guess this is not the most efficient way.

Thank you very much!

**Comment by adrai** [comment]
No at the moment there is no api that does this... but may I ask why you need it? What is your intend?

**Comment by NilsFrkal** [comment]
Re: [node-eventstore] Only Getting Undispatched Items per StreamID (#45)


Thanks for getting back to me ... here is my scenario:

My users can be online or offline. My backend doesn't know about the sessions as this is managed in nodejs/sessions/redis. So all "relevant events" are send out and stored in your event store (pretty cool stuff by the way ...). Anyway, I can have 2 situations: 

A) user is currently logged in with 1 or more devices. In this case I broadcast the events up to the channel immediately
B) user is offline. In this case I just store the events until ... user comes online

-> here is the problem. As soon as the user logs in I need to broadcast the undispatched events. But I can only get them by going through all undispatched events. Unfortunately I am looking at "pretty high volume event and not so many people logged" in scenario most of the times. So this becomes fairly expensive.

I am just wondering how you solved this in the "add event" scenario as in this case it is based on streamId?

Cheers, Nils

**Comment by adrai** [comment]
ok? https://github.com/adrai/node-eventstore#own-event-dispatching-no-event-publisher-function-defined
v1.5.0

**Comment by NilsFrkal** [comment]
Awsome! Works like charm ... Thanks Adrai. Much appreciated.
