### ISSUE TITLE
mongodb driver authSource authentication option not supported.

### ISSUE THREAD

**Issue by TheolZacharopoulos** [adrai/node-eventstore#46]
The module does not support mongodb authentication through a database, (no authSource on the authentication options) 
https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html#auth-options

**Comment by adrai** [comment]
Can you make a PR?

**Comment by TheolZacharopoulos** [comment]
Sure!

**Comment by TheolZacharopoulos** [comment]
Done in https://github.com/adrai/node-eventstore/pull/47
