### ISSUE TITLE
Could I query the event data through event.payload data such as parent.event.payload? 

### ISSUE THREAD

**Issue by liangzeng** [adrai/node-eventstore#55]
Could I query the event data through event.payload data such as event.payload.parent? 

Could you show me an example?

    store.findEvents({payload:{parent:["parentA","parentB"]}} ... )  ?

**Comment by liangzeng** [comment]
store.findEvents({payload:{parent:["parentA","parentB"]}} ... )  ?

**Comment by adrai** [comment]
no
