### ISSUE TITLE
Support for mongodb uri connection strings 

### ISSUE THREAD

**Issue by danwkennedy** [adrai/node-eventstore#68]
We construct mongo connection [strings](https://docs.mongodb.org/manual/reference/connection-string/) and I was wondering if that is supported in this module. I'm mainly asking because we use the different options pretty heavily depending on the environment (local doesn't use a replica set whereas production does).

**Comment by adrai** [comment]
Url no... But replSet yes: https://github.com/adrai/node-eventstore/blob/master/lib/databases/mongodb.js#L53

**Comment by danwkennedy** [comment]
Looks like other related options are being omitted in that case. Our DevOps types would like to manage things like the read preference, write preference, replica set name, etc.

This is mainly the reason why we switched to handling URL's. There are nifty generator libraries that'll abstract them out for you such as https://www.npmjs.com/package/mongodb-uri

**Comment by adrai** [comment]
If you want you can try to do a PR an I will try to merge it asap, ok?

**Comment by danwkennedy** [comment]
Sure thing, I'll see what I can do.

**Comment by danwkennedy** [comment]
@adrai are all the the unit tests passing in master? I'm getting failing tests locally and was wondering if I need to do something special to get them working.

**Comment by adrai** [comment]
if inmemory stuff works locally then you can try a PR

**Comment by danwkennedy** [comment]
K, I'll cleanup some stuff and set it up
