### ISSUE TITLE
Updating to ES2015/16/17

### ISSUE THREAD

**Issue by johanneslumpe** [adrai/node-eventstore#79]
It would be nice to update the codebase to a newer version of JavaScript for less verbose and potentially more readable code. If there is an interest in this I'd offer to send a PR, as it would also give me an excuse to thoroughly dig through the codebase.

**Comment by adrai** [comment]
At the moment we support older version of node i.e. 0.10 or even 0.8
I think we should wait a bit... but as soon as nobody is interested in this old versions anymore we could update the code...

**Comment by johanneslumpe** [comment]
We could still use Babel to transpile the code so that it works in older node versions. But apart from that, 0.8 and 0.10 are obsolete versions.

**Comment by adrai** [comment]
I'm a big fan of transpiling for frontend... but not for backend...
I would update the code directly to be compatible with node v6.x LTS but we have to wait a bit...

**Comment by johanneslumpe** [comment]
Ah ok. Just out of curiosity: why don't you like transpiling on the backend? Not trying to force anything here, just genuinely curious.

**Comment by adrai** [comment]
tabs vs. spaces ;-)

**Comment by johanneslumpe** [comment]
:D
