### ISSUE TITLE
[Question] How battle-tested/stable is the library

### ISSUE THREAD

**Issue by johanneslumpe** [adrai/node-eventstore#80]
@adrai I assume that you have been using the library for a few projects at least? If so, could you give some insights into the stability/durability of the project? Any kind of feedback would be appreciated 👍

**Comment by adrai** [comment]
I can just say... that this library is used in multiple projects in production environments.
The best db implementation perhaps is mongodb.

**Comment by johanneslumpe** [comment]
Ok cool, thanks!
