### ISSUE TITLE
[redis] aggregates versioning might be inconsistent

### ISSUE THREAD

**Issue by rehia** [adrai/node-eventstore#90]
While I was trying to use snapshots with redis, I ran into an issue which causes bugs when reloading my stream.
In some cases, and often under heavy load, redis store can produce multiple events with the same revision. So at a moment, the number of events (eg. 15) is higher than the current revision (eg 13, event revision 5 and 6 are "duplicated").
The problem starts when loading a snapshot and the corresponding events. The last snapshot is created with revision 13. And when the snapshot is loaded, events with revision above 13 are loaded with it, so mainly the 2 latest events (revisions 12 and 13), causing an inconsistent state when reloading from snapshot and events.

The problem is caused by the fact that the `streamRevision` of an event is based on the last loaded event, here https://github.com/adrai/node-eventstore/blob/663fb9fc3d0765ae22196c1bff3ea9aa8e79b305/lib/eventstore.js#L402-L413
Because this operation is not atomic, under heavy load or with lots of events, another command on the aggregate can cause the load of the aggregate with the same events, before the first one had enough time to commit. Both generated events finally get the same revision.

The problem is not directly in redis store. And I don't know if other stores face the same issue (using transactions ?). There is no transaction in redis, only atomic operations using `MULTI` (with no dependency on intermediate results) or Lua scripts (when needing to execute an operation depending on the previous result).

I open this ticket to open the discussion on this. I was thinking about a solution, but only for redis: instead of calling directly a `SET`, we could create a Lua script (easily deployed with redis driver, with all the caching stuff) which could `INCR` a value corresponding to the actual revision of an aggregate, and use it as the `streamRevision`, and then make the `SET`. Can't be safer, all is done atomically. And hopefully, redis loads natively a JSON library for Lua. But the problem is that the stream loaded in memory is no longer in sync. It could causes  

Don't hesitate to contribute to this thread. I would love to hear your thoughts. In the mean time, I'll try to make a PR to show my intent.

**Comment by rehia** [comment]
Actually, it's possible to re-sync stream by returning the generated streamRevision from Lua script :)

**Comment by adrai** [comment]
You're right. In all cqrs systems I'm active, the system guarantee that all commands of aggragate (event-stream) are passed to the same worker with the help of (i.e. rabbitmq consistent hash exchange and cqrs-domain, etc...)
But everything, that makes node-eventstore better is a good thing ;-)
