### ISSUE TITLE
Error: The events passed should all have a streamRevision!

### ISSUE THREAD

**Issue by pingchen** [adrai/node-eventstore#98]
I got the following error when I try to write an event into event store which is empty:

```
Error: The events passed should all have a streamRevision!
    at Object.EventStream ([projectDirectory]/node_modules/eventstore/lib/eventStream.js:52:15)
    at [projectDirectory]/node_modules/eventstore/lib/eventstore.js:284:22
    at[projectDirectory]/node_modules/eventstore/lib/databases/mongodb.js:333:16
    at handleCallback ([projectDirectory]/node_modules/mongodb/lib/utils.js:95:12)

```
We are still using nodejs 0.12.7. I traced down to the line 52 in eventStream.js.  It appears that, when the events is [], the code is still managed to reach line 49 to cause to crash.

After I changed the line 47-48 to
```
   for(var i=0, len=events.length; i < len; i++) {
      var evt = events[i];
```
The crash problem stops.

**Comment by adrai** [comment]
Can you submit a Pull request?
